[toolchain]

[features]
seeds = false,
skip-lint = false

[programs.localnet]
caterpillar_contract = "EMh2kNfPQVMvJ4JA5Exzrz55FSHXnZmrxGAJyr8WWan"

[programs.devnet]
caterpillar_contract = "EMh2kNfPQVMvJ4JA5Exzrz55FSHXnZmrxGAJyr8WWan"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/king/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
